SELECT A1.Name, A2.Name, COUNT(*) AS N
FROM (ACTOR A1 NATURAL JOIN MOVIE_ACTOR M1)
JOIN (ACTOR A2 NATURAL JOIN MOVIE_ACTOR M2) USING (MovieId)
WHERE A1.Name < A2.Name
GROUP BY A1.Name, A2.Name
HAVING N >= 4
ORDER BY N DESC, A1.Name, A2.Name;
