UPDATE STREAM
SET Charge = 4.5
WHERE CustomerId NOT IN (
	SELECT CustomerId
	FROM CUSTOMER
	JOIN COUNTRY ON (CUSTOMER.Country = COUNTRY.Name)
	JOIN REGION USING (RegionId)
	WHERE REGION.Name = 'Africa'
)
AND MovieId IN (
	SELECT MovieId
	FROM MOVIE
	NATURAL JOIN MOVIE_GENRE
	NATURAL JOIN GENRE
  WHERE Year < 1985 AND Label = 'Sci-fi'
);
