SELECT Label, REGION.Name, COUNT(StreamId) AS N
FROM GENRE
JOIN REGION
LEFT OUTER JOIN (
	MOVIE_GENRE
  JOIN COUNTRY
	JOIN CUSTOMER ON (CUSTOMER.Country = COUNTRY.Name)
  JOIN STREAM USING (MovieId, CustomerId)
) USING (GenreId, RegionId)
GROUP BY Label, REGION.Name
ORDER BY Label, REGION.Name;
