DROP VIEW STREAM_COUNT_BY_COUNTRY;

CREATE VIEW STREAM_COUNT_BY_COUNTRY(Country,StreamCount)
AS
SELECT COUNTRY.Name, COUNT(STREAM.StreamId)
FROM CUSTOMER
JOIN COUNTRY ON (COUNTRY.Name = CUSTOMER.Country)
LEFT OUTER JOIN STREAM USING (CustomerId)
GROUP BY Country;
