SELECT M.Title
FROM MOVIE M
NATURAL JOIN MOVIE_GENRE MG
NATURAL JOIN GENRE G
WHERE G.Label = 'Action'
AND MovieId IN (
  SELECT MovieId
  FROM MOVIE_GENRE MG
  NATURAL JOIN GENRE G
  WHERE G.Label = 'Comedy'
)
ORDER BY M.Title;
