DELETE FROM MOVIE_ACTOR
WHERE MovieId IN (
  SELECT MovieId
  FROM MOVIE
  NATURAL JOIN MOVIE_GENRE
  NATURAL JOIN GENRE
  WHERE GENRE.Label = 'Action'
)
AND MovieId NOT IN (
  SELECT MovieId
  FROM STREAM
);
