SELECT A1.Name, A2.Name, COUNT(DISTINCT(M.MovieId)) AS Participations, COUNT(S.StreamId) AS Streams
FROM (ACTOR A1 NATURAL JOIN MOVIE_ACTOR MA1)
JOIN (ACTOR A2 NATURAL JOIN MOVIE_ACTOR MA2) USING (MovieId)
NATURAL JOIN MOVIE M
NATURAL JOIN STREAM S
WHERE A1.Name < A2.Name
GROUP BY A1.Name, A2.Name
HAVING Streams >= 40
ORDER BY Streams DESC, Participations DESC, A1.Name, A2.Name;
