SELECT COUNTRY.Name, GENRE.Label, COUNT(STREAM.StreamId)
FROM GENRE
NATURAL JOIN MOVIE_GENRE
JOIN CUSTOMER
JOIN COUNTRY ON CUSTOMER.Country = COUNTRY.Name
JOIN REGION USING (RegionId)
LEFT OUTER JOIN STREAM USING (MovieId, CustomerId)
WHERE REGION.Name = 'Other Countries'
GROUP BY COUNTRY.Name, GENRE.Label
ORDER BY COUNTRY.Name, GENRE.Label
;
